config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :urls
  # # Overide default devise controllers
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # sessions: 'users/sessions',
    # confirmations: 'users/confirmations',
    # unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :users
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  root 'urls#new'

  match ':short_url' => 'urls#redirect', via: [:get]
end

app/models/url.rb
# frozen_string_literal: true
class Url < ApplicationRecord
  validates :full_url, :http_status, presence: true
  validates :short_url, uniqueness: true

  before_create :generate_short_url
  before_create :sanitize

  private

  def generate_short_url
    self.short_url = SecureRandom.hex(3)
  end

  def sanitize
    self.full_url = "http://#{full_url}" unless full_url =~ %r{^https?:\/\/}
  end
end

app/controllers/urls_controller.rb
# frozen_string_literal: true
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  def redirect
    @link = Url.find_by(short_url: params[:short_url])
    if @link
      redirect_to @link.full_url, status: @link.http_status
    else
      not_found
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_url
    @url = Url.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def url_params
    params.require(:url).permit(:short_url, :full_url, :http_status, :clicks)
  end
end

app/helpers/urls_helper.rb
# frozen_string_literal: true
module UrlsHelper
  def shortened_url(params)
    "#{request.base_url}/#{params}"
  end
end

app/views/urls/_form.html.slim
ruby:
  if local_assigns.has_key? :remote
    remote = remote
  else
    remote = false
  end


= form_for @url, html: { class: 'ui form' }, remote: remote do |f|

  - if @url.errors.any?
    #error_explanation
      h2 = "#{pluralize(@url.errors.count, "error")} prohibited this url from being saved:"
      ul
        - @url.errors.full_messages.each do |message|
          li = message

  /.field
    = f.label :short_url
    = f.text_field :short_url

  .field
    = f.label :full_url

    .ui.labeled.input
      .ui.label
        | http://
      = f.text_field :full_url, placeholder: "mysite.com"

  /.field
    = f.label :http_status
    = f.number_field :http_status

  /.field
    = f.label :clicks
    = f.number_field :clicks

  .field
    = f.submit 'Shorten', class: 'ui button primary'

app/views/urls/_short_url.html.slim
.ui.form
  .field

    h3 Shortened url:
    p
      b
        = shortened_url(@url.short_url)
    br
      / TODO Implement JS copy to clipboard
        button class="ui teal right labeled icon button"
          i class="copy icon"
          | Copy

app/views/urls/create.js.erb
$('#response').html("<%= escape_javascript(render('short_url')) %>");

app/views/urls/edit.html.slim
h1 Editing url

== render 'form'

= link_to 'Show', @url
'  |
= link_to 'Back', urls_path

app/views/urls/index.html.slim
h1 Listing urls

table
  thead
    tr
      th Short url
      th Full url
      th Http status
      th Clicks
      th
      th
      th

  tbody
    - @urls.each do |url|
      tr
        td = shortened_url(url.short_url)
        td = url.full_url
        td = url.http_status
        td = url.clicks
        td = link_to 'Show', url
        td = link_to 'Edit', edit_url_path(url)
        td = link_to 'Destroy', url, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Url', new_url_path

app/views/urls/new.html.slim
h1 New url

p Enter the Url you would like to shorten below

#response

= render 'form', remote: true

app/views/urls/show.html.slim
p#notice = notice

p
  strong
    ' Short url:
  = shortened_url(@url.short_url)

p
  strong
    ' Full url:
  = @url.full_url
p
  strong
    ' Http status:
  = @url.http_status
p
  strong
    ' Clicks:
  = @url.clicks

= link_to 'Edit', edit_url_path(@url)
'  |
= link_to 'Back', urls_path